/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.ucm.poker3.view.mainFrame;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.ucm.poker3.main.Main;

public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
        this.setTitle("Practica 3");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //Image fondo = new ImageIcon(getClass().getResource("/resources/fondos/FondoMain.png"));
        //this.add(new MainPanel());
        //this.add(new JLabel(new ImageIcon("/resources/fondos/FondoMain.png")));
        //BufferedImage fondo = ImageIO.read(new java.net.URL())
        Graphics g = null;
        MainPanel mP =new MainPanel(g);
        this.add(mP);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
